// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZD_ZsITswOM-K-cAg8PL9wbGkOTfSLyI',
    appId: '1:114010132422:web:b1329c80626f0fd07cacc7',
    messagingSenderId: '114010132422',
    projectId: 'rummikub-solver-360e1',
    authDomain: 'rummikub-solver-360e1.firebaseapp.com',
    storageBucket: 'rummikub-solver-360e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTnwzfIOeNV9-QblDZgUGH4u6xoF2b-do',
    appId: '1:114010132422:android:3c4cf41fcbe8f9ce7cacc7',
    messagingSenderId: '114010132422',
    projectId: 'rummikub-solver-360e1',
    storageBucket: 'rummikub-solver-360e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnV0ih1t9gtlJq8d0fHp7Vonf6jcXJH7Y',
    appId: '1:114010132422:ios:999df31ed9d0fc547cacc7',
    messagingSenderId: '114010132422',
    projectId: 'rummikub-solver-360e1',
    storageBucket: 'rummikub-solver-360e1.firebasestorage.app',
    iosBundleId: 'com.example.rummikubAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnV0ih1t9gtlJq8d0fHp7Vonf6jcXJH7Y',
    appId: '1:114010132422:ios:f6f460c16a994dd37cacc7',
    messagingSenderId: '114010132422',
    projectId: 'rummikub-solver-360e1',
    storageBucket: 'rummikub-solver-360e1.firebasestorage.app',
    iosBundleId: 'com.example.rummikubAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZD_ZsITswOM-K-cAg8PL9wbGkOTfSLyI',
    appId: '1:114010132422:web:c79550acbc96b0487cacc7',
    messagingSenderId: '114010132422',
    projectId: 'rummikub-solver-360e1',
    authDomain: 'rummikub-solver-360e1.firebaseapp.com',
    storageBucket: 'rummikub-solver-360e1.firebasestorage.app',
  );
}
